### ISSUE TITLE
Bridge nicht konfigurierbar

### ISSUE THREAD

**Issue by Matten-Matten** [ptweety/node-red-contrib-ccu-jack#1]
Hallo, ich kann Die Bridge Settings nicht einstellen (Nodered 4.0.2, Jack 2.9.2)

![Screenshot 2024-10-30 095009](https://github.com/user-attachments/assets/76c1a6a5-3396-4739-87fb-7acced737c74)

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
![Screenshot 2024-10-30 100429](https://github.com/user-attachments/assets/2b5143ac-086b-4482-a1bc-6219b2f838d8)

**Comment by ptweety** [comment]
Hi @Matten-Matten,
hast du zufällig in deiner `settings.js` diese Variable gesetzt: `process.env.NRCCJ_DEV = true;`? Wenn ja, bitte mal auskommentieren: `//...`

**Comment by Matten-Matten** [comment]
Hey,
Normal nicht , ich hatte das auch auf meinem Testsystem installiert, um mich damit vertraut zu machen. Nach dem importieren der bsp flows wurden mir die Bridge node mit config Fehler angezeigt.

**Comment by ptweety** [comment]
Ok, hast du irgendwelche Fehler im Editor? Und siehst du was im Log?

**Comment by ptweety** [comment]
fixed by 07c5379317d52b5734a46cd2c1adc79a298f6d4b
